name: Update Bedrock Server Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python update.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated bedrock server data